P6Math/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib import admin
from django.urls import include, path
urlpatterns = [
    path('polls/', include('polls.urls')),
    path('science/', include('science.urls')),
    path('admin/', admin.site.urls),
]
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

polls/urls.py
from django.urls import path

from . import views

#urlpatterns = [
#    path('', views.index, name='index'),
#]
from . import views
app_name = 'polls'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

science/urls.py
from django.urls import path

from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

#urlpatterns = [
#    path('', views.index, name='index'),
#]
from . import views
app_name = 'science'


urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('science_report/', views.ScienceReportView.as_view(), name='science_report'),
    path('science_mcq/', views.ScienceMCQView.as_view(), name='science_mcq'),
    path('science_open/', views.ScienceOpenView.as_view(), name='science_open'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('generate_science_report', views.generate_science_report, name='generate_science_report'),
    path('science_reportresult/', views.ScienceReportresultView.as_view(), name='science_reportresult'),
    path('english_report/', views.EnglishReportView.as_view(), name='english_report'),
    path('english_mcq/', views.EnglishMCQView.as_view(), name='english_mcq'),
    path('english_open/', views.EnglishOpenView.as_view(), name='english_open'),
    path('english_reportresult/', views.EnglishReportresultView.as_view(), name='english_reportresult'),
    path('generate_english_report', views.generate_english_report, name='generate_english_report'),

]

urlpatterns += staticfiles_urlpatterns()

science/models.py
import datetime

from django.db import models
from django.db.models import Model
from django.utils import timezone


class ScienceQuestion(models.Model):
    question_model_index = models.CharField(max_length=200, default='000')
    question_model = models.CharField(max_length=2000, default='NA')
    question_text = models.CharField(max_length=2000, default='*')
    pub_date = models.DateTimeField('date published')
    correct_answer_a = models.CharField(max_length=20, default='0')
    attempted_answer_a = models.CharField(max_length=500, default='0')
    correct_answer_b = models.CharField(max_length=500, default='0')
    attempted_answer_b = models.CharField(max_length=500, default='0')
    correct_answer_c = models.CharField(max_length=500, default='0')
    attempted_answer_c = models.CharField(max_length=500, default='0')
    attempted_answer_d = models.CharField(max_length=500, default='0')
    result_text = models.CharField(max_length=2000, default='')
    topic_number = models.CharField(max_length=20, default='1')
    subtopic_number = models.CharField(max_length=50, default='1')
    lv3_topic_number = models.CharField(max_length=50, default='0')
    number_of_attempts = models.IntegerField(default=0)
    number_of_successful_attempts = models.IntegerField(default=0)
    image_name = models.CharField(max_length=200, default='000_01.png')
    image2_name = models.CharField(max_length=200, default='000_02.png')
    question_additional_text_line_1 = models.CharField(max_length=500, default='*')
    question_additional_text_line_2 = models.CharField(max_length=500, default='*')
    question_additional_text_line_3 = models.CharField(max_length=500, default='*')
    question_additional_text_line_4 = models.CharField(max_length=500, default='*')
    question_source = models.CharField(max_length=100, default='')
    success_on_first_attempt = models.CharField(max_length=10, default='No')
    last_attempt_date = models.CharField(max_length=50, default='0')
    last_attempt_success = models.CharField(max_length=50, default='No')
    first_self_rated_score = models.IntegerField(default=-1)
    latest_self_rated_score = models.IntegerField(default=-1)
    answer_image_name = models.CharField(max_length=200, default='default_pic.png')
    question_type = models.CharField(max_length=200, default='MCQ')
    question_subject = models.CharField(max_length=200, default='Science')

    #pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class ScienceChoice(models.Model):
    question = models.ForeignKey(ScienceQuestion, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    answer = models.CharField(max_length=10, default='')

    def __str__(self):
        return self.choice_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

class ScienceTopic(models.Model):
    topic_index = models.CharField(max_length=10, default='0')
    topic_name = models.CharField(max_length=500, default='0')
    number_of_questions = models.IntegerField(default=0)
    number_of_attempted_questions = models.IntegerField(default=0)
    number_of_success_first_attempt = models.IntegerField(default=0)
    number_of_latest_success_attempt = models.IntegerField(default=0)
    number_of_attempted_open_questions = models.IntegerField(default=0)
    avg_first_self_rated_score = models.FloatField(default=0.0)
    avg_latest_self_rated_score = models.FloatField(default=0.0)


class ScienceSubTopic(models.Model):
    topic_index = models.CharField(max_length=10, default='0')
    topic_name = models.CharField(max_length=500, default='0')
    number_of_questions = models.IntegerField(default=0)
    number_of_attempted_questions = models.IntegerField(default=0)
    number_of_success_first_attempt = models.IntegerField(default=0)
    number_of_latest_success_attempt = models.IntegerField(default=0)
    number_of_attempted_open_questions = models.IntegerField(default=0)
    avg_first_self_rated_score = models.FloatField(default=0.0)
    avg_latest_self_rated_score = models.FloatField(default=0.0)

class ScienceLevel3Topic(models.Model):
    topic_index = models.CharField(max_length=10, default='0')
    topic_name = models.CharField(max_length=500, default='0')
    number_of_questions = models.IntegerField(default=0)
    number_of_attempted_questions = models.IntegerField(default=0)
    number_of_success_first_attempt = models.IntegerField(default=0)
    number_of_latest_success_attempt = models.IntegerField(default=0)
    number_of_attempted_open_questions = models.IntegerField(default=0)
    avg_first_self_rated_score = models.FloatField(default=0.0)
    avg_latest_self_rated_score = models.FloatField(default=0.0)


#English

class EnglishQuestion(models.Model):
    question_model_index = models.CharField(max_length=200, default='000')
    question_model = models.CharField(max_length=2000, default='NA')
    question_text = models.CharField(max_length=2000, default='*')
    pub_date = models.DateTimeField('date published')
    correct_answer_a = models.CharField(max_length=20, default='0')
    attempted_answer_a = models.CharField(max_length=500, default='0')
    correct_answer_b = models.CharField(max_length=500, default='0')
    attempted_answer_b = models.CharField(max_length=500, default='0')
    correct_answer_c = models.CharField(max_length=500, default='0')
    attempted_answer_c = models.CharField(max_length=500, default='0')
    attempted_answer_d = models.CharField(max_length=500, default='0')
    result_text = models.CharField(max_length=2000, default='')
    topic_number = models.CharField(max_length=20, default='1')
    subtopic_number = models.CharField(max_length=50, default='1')
    lv3_topic_number = models.CharField(max_length=50, default='0')
    number_of_attempts = models.IntegerField(default=0)
    number_of_successful_attempts = models.IntegerField(default=0)
    image_name = models.CharField(max_length=200, default='000_01.png')
    image2_name = models.CharField(max_length=200, default='000_02.png')
    question_additional_text_line_1 = models.CharField(max_length=500, default='*')
    question_additional_text_line_2 = models.CharField(max_length=500, default='*')
    question_additional_text_line_3 = models.CharField(max_length=500, default='*')
    question_additional_text_line_4 = models.CharField(max_length=500, default='*')
    question_source = models.CharField(max_length=100, default='')
    success_on_first_attempt = models.CharField(max_length=10, default='No')
    last_attempt_date = models.CharField(max_length=50, default='0')
    last_attempt_success = models.CharField(max_length=50, default='No')
    first_self_rated_score = models.IntegerField(default=-1)
    latest_self_rated_score = models.IntegerField(default=-1)
    answer_image_name = models.CharField(max_length=200, default='default_pic.png')
    question_type = models.CharField(max_length=200, default='MCQ')
    question_subject = models.CharField(max_length=200, default='Science')



    #pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class EnglishChoice(models.Model):
    question = models.ForeignKey(ScienceQuestion, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    answer = models.CharField(max_length=10, default='')

    def __str__(self):
        return self.choice_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

class EnglishTopic(models.Model):
    topic_index = models.CharField(max_length=10, default='0')
    topic_name = models.CharField(max_length=500, default='0')
    number_of_questions = models.IntegerField(default=0)
    number_of_attempted_questions = models.IntegerField(default=0)
    number_of_success_first_attempt = models.IntegerField(default=0)
    number_of_latest_success_attempt = models.IntegerField(default=0)
    number_of_attempted_open_questions = models.IntegerField(default=0)
    avg_first_self_rated_score = models.FloatField(default=0.0)
    avg_latest_self_rated_score = models.FloatField(default=0.0)


class EnglishSubTopic(models.Model):
    topic_index = models.CharField(max_length=10, default='0')
    topic_name = models.CharField(max_length=500, default='0')
    number_of_questions = models.IntegerField(default=0)
    number_of_attempted_questions = models.IntegerField(default=0)
    number_of_success_first_attempt = models.IntegerField(default=0)
    number_of_latest_success_attempt = models.IntegerField(default=0)
    number_of_attempted_open_questions = models.IntegerField(default=0)
    avg_first_self_rated_score = models.FloatField(default=0.0)
    avg_latest_self_rated_score = models.FloatField(default=0.0)

class EnglishLevel3Topic(models.Model):
    topic_index = models.CharField(max_length=10, default='0')
    topic_name = models.CharField(max_length=500, default='0')
    number_of_questions = models.IntegerField(default=0)
    number_of_attempted_questions = models.IntegerField(default=0)
    number_of_success_first_attempt = models.IntegerField(default=0)

science/forms.py
from django import forms

class ReceiveAnswer(forms.Form):
    answer_returned = forms.DecimalField(help_text="Enter Your Answer")
    

science/templates/science/detail.html
<a href="http://192.168.18.10:8000/science/">Go Home</a>

<h3>{{ sciencequestion.question_text }}</h3>

(Source: {{ sciencequestion.question_source }})<BR><BR>
{{ sciencequestion.question_additional_text_line_1 }}<BR>
{{ sciencequestion.question_additional_text_line_2 }}<BR>
{{ sciencequestion.question_additional_text_line_3 }}<BR>
{{ sciencequestion.question_additional_text_line_4 }}<BR>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
{% load static %} <img src="{% static 'science/media/' %}{{sciencequestion.image_name}}" alt="home" />
{% load static %} <img src="{% static 'science/media/' %}{{sciencequestion.image2_name}}" alt="home" />

<BR><BR>

<form action="{% url 'science:vote' sciencequestion.id %}" method="post">
{% csrf_token %}
{% for sciencechoice in sciencequestion.sciencechoice_set.all %}
    <!--  <input type="radio" name="sciencechoice" id="sciencechoice{{ forloop.counter }}" value="{{ sciencechoice.id }}">
     <label for="sciencechoice{{ forloop.counter }}">{{ sciencechoice.choice_text }}</label><br>
     -->
    {{sciencechoice.choice_text}} <br>
{% endfor %}
<BR><BR>


You answer (Part a) <input type = "text", name="attempted_answer_a", id="attempted_answer_a" value="" size="100"> <BR>
<BR>

The following is only applicable for open ended questions. <BR>
Part b)
<input type = "text", name="attempted_answer_b", id="attempted_answer_b" value="" size="100"> <BR>
Part c)
<input type = "text", name="attempted_answer_c", id="attempted_answer_c" value="" size="100"> <BR>
Part d)
<input type = "text", name="attempted_answer_d", id="attempted_answer_d" value="" size="100"> <BR>
<BR><BR>
Self-Rated Score (out of 10) for Open Questions Only
<input type = "text", name="self_rated_score", id="self_rated_score" value=""> <BR>

    <BR>
<input type="submit" value="Submit Answer">

<BR><BR><BR><BR><BR><BR><BR><BR><BR><BR><BR><BR><BR><BR><BR><BR><BR><BR><BR><BR><BR>
<BR><BR><BR><BR><BR><BR><BR><BR><BR><BR><BR><BR><BR><BR><BR><BR><BR><BR><BR><BR><BR>
<BR><BR><BR><BR><BR><BR><BR><BR><BR><BR><BR><BR><BR><BR><BR><BR><BR><BR><BR><BR><BR>

{% load static %} <img src="{% static 'science/media/' %}{{sciencequestion.answer_image_name}}" alt="home" />

</form>

science/templates/science/english_mcq.html
<a href="http://192.168.18.10:8000/science/">Go Home</a>
<BR><BR>

{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'science/style.css' %}">

List of English MCQ Questions <BR>
{% if english_mcq_question_list %}
    <ul>
    {% for question in english_mcq_question_list %}
        <li><a href="{% url 'science:detail' question.id %}">{{ question.question_model_index }}</a></li>
    {% endfor %}
    </ul>
{% endif %}
<BR><BR>


<BR><BR>

science/templates/science/english_open.html
<a href="http://192.168.18.10:8000/science/">Go Home</a>
<BR><BR>

{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'science/style.css' %}">

List of English Open Questions <BR>
{% if english_open_question_list %}
    <ul>
    {% for question in english_open_question_list %}
        <li><a href="{% url 'science:detail' question.id %}">{{ question.question_model_index }}</a></li>
    {% endfor %}
    </ul>
{% endif %}
<BR><BR>


<BR><BR>

science/templates/science/english_report.html
<a href="http://192.168.18.10:8000/science/">Go Home</a>
<BR><BR>

{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'science/style.css' %}">

List of
<BR>
1) MCQ Questions with Unsuccessful First Attempt and
<BR>
2) Open Question with First Self Rated Score Less Than 8 <BR>
{% if failed_question_list %}
    <ul>
    {% for question in failed_question_list %}
        <li><a href="{% url 'science:detail' question.id %}">{{ question.question_model_index }}</a></li>
    {% endfor %}
    </ul>
<BR><BR>
<form action="{% url 'science:generate_english_report' %}" method="post">
{% csrf_token %}
<input type="submit" value="English Full Report">


<BR><BR>

science/templates/science/english_reportresult.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'science/style.css' %}">


        Topic Index;Number of Questions;Number of Attempted Questions (MCQ+Open); Number of success first attempt for MCQ Questions;Number of success last attempt for MCQ Questions;Average Score of Open Questions-First Attempt;Average Score of Open Questions-Latest Attempt
{% if level1_topic_list %}
    <ul>
    {% for tp in level1_topic_list %}
        {{ tp.topic_index }} {{ tp.topic_name }};{{ tp.number_of_questions }};{{ tp.number_of_attempted_questions }};{{ tp.number_of_success_first_attempt }};{{ tp.number_of_latest_success_attempt }};{{ tp.avg_first_self_rated_score }};{{ tp.avg_latest_self_rated_score }} <BR>
    {% endfor %}
    </ul>
{% endif %}
{% if level2_topic_list %}
    <ul>
    {% for tp in level2_topic_list %}
        {{ tp.topic_index }} {{ tp.topic_name }};{{ tp.number_of_questions }};{{ tp.number_of_attempted_questions }};{{ tp.number_of_success_first_attempt }};{{ tp.number_of_latest_success_attempt }};{{ tp.avg_first_self_rated_score }};{{ tp.avg_latest_self_rated_score }} <BR>
    {% endfor %}
    </ul>
{% endif %}
{% if level3_topic_list %}
    <ul>
    {% for tp in level3_topic_list %}
        {{ tp.topic_index }} {{ tp.topic_name }};{{ tp.number_of_questions }};{{ tp.number_of_attempted_questions }};{{ tp.number_of_success_first_attempt }};{{ tp.number_of_latest_success_attempt }};{{ tp.avg_first_self_rated_score }};{{ tp.avg_latest_self_rated_score }} <BR>
    {% endfor %}
    </ul>
{% endif %}

science/templates/science/index.html
{% load static %}

   {% if user.is_authenticated %}
     <li>User: {{ user.get_username }}</li>
     <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
   {% else %}
     <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
   {% endif %}

<BR><BR><BR>
<link rel="stylesheet" type="text/css" href="{% static 'science/style.css' %}">
<a href = "/science/science_report/"> Science Report </a>
<BR>
<a href = "/science/english_report/"> English Report </a>
<BR>
<a href = "/science/science_mcq/"> Science MCQ Questions </a>
<BR>
<a href = "/science/science_open/"> Science Open Questions </a>
<BR>
<a href = "/science/english_mcq/"> English MCQ Questions </a>
<BR>
<a href = "/science/english_open/"> English Open Questions </a>

<BR><BR><BR>
<a href = "/accounts/logout/"> Logout </a>


<!--
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'science:detail' question.id %}">{{ question.question_model_index }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No questions are available.</p>
{% endif %}
-->

science/templates/science/results.html
<a href="http://192.168.18.10:8000/science">Go Home</a>
<BR>
<h3>{{ sciencequestion.question_text }}</h3>

<ul>
{% for sciencechoice in sciencequestion.sciencechoice_set.all %}
    <!--
    <li>{{ sciencechoice.choice_text }} -- {{ sciencechoice.votes }} vote{{ sciencechoice.votes|pluralize }}</li>
    -->
    {{sciencechoice.choice_text}}<br>
{% endfor %}
</ul>

{{sciencequestion.result_text}}
<br>
<br>

<a href="{% url 'science:detail' sciencequestion.id %}">Try again?</a>

science/templates/science/science_mcq.html
<a href="http://192.168.18.10:8000/science/">Go Home</a>
<BR><BR>

{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'science/style.css' %}">

List of Science MCQ Questions <BR>
{% if science_mcq_question_list %}
    <ul>
    {% for question in science_mcq_question_list %}
        <li><a href="{% url 'science:detail' question.id %}">{{ question.question_model_index }}</a></li>
    {% endfor %}
    </ul>
{% endif %}
<BR><BR>


<BR><BR>

science/templates/science/science_open.html
<a href="http://192.168.18.10:8000/science/">Go Home</a>
<BR><BR>

{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'science/style.css' %}">

List of Science Open Questions <BR>
{% if science_open_question_list %}
    <ul>
    {% for question in science_open_question_list %}
        <li><a href="{% url 'science:detail' question.id %}">{{ question.question_model_index }}</a></li>
    {% endfor %}
    </ul>
{% endif %}
<BR><BR>


<BR><BR>

science/templates/science/science_report.html
<a href="http://192.168.18.10:8000/science/">Go Home</a>
<BR><BR>

{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'science/style.css' %}">

List of
<BR>
1) MCQ Questions with Unsuccessful First Attempt and
<BR>
2) Open Question with First Self Rated Score Less Than 8 <BR>
{% if failed_question_list %}
    <ul>
    {% for question in failed_question_list %}
        <li><a href="{% url 'science:detail' question.id %}">{{ question.question_model_index }}</a></li>
    {% endfor %}
    </ul>
{% endif %}
<BR><BR>
<form action="{% url 'science:generate_science_report' %}" method="post">
{% csrf_token %}
<input type="submit" value="Generate Full Report">


<BR><BR>

science/templates/science/science_reportresult.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'science/style.css' %}">


        Topic Index;Number of Questions;Number of Attempted Questions (MCQ+Open); Number of success first attempt for MCQ Questions;Number of success last attempt for MCQ Questions;Average Score of Open Questions-First Attempt;Average Score of Open Questions-Latest Attempt
{% if level1_topic_list %}
    <ul>
    {% for tp in level1_topic_list %}
        {{ tp.topic_index }} {{ tp.topic_name }};{{ tp.number_of_questions }};{{ tp.number_of_attempted_questions }};{{ tp.number_of_success_first_attempt }};{{ tp.number_of_latest_success_attempt }};{{ tp.avg_first_self_rated_score }};{{ tp.avg_latest_self_rated_score }} <BR>
    {% endfor %}
    </ul>
{% endif %}
{% if level2_topic_list %}
    <ul>
    {% for tp in level2_topic_list %}
        {{ tp.topic_index }} {{ tp.topic_name }};{{ tp.number_of_questions }};{{ tp.number_of_attempted_questions }};{{ tp.number_of_success_first_attempt }};{{ tp.number_of_latest_success_attempt }};{{ tp.avg_first_self_rated_score }};{{ tp.avg_latest_self_rated_score }} <BR>
    {% endfor %}
    </ul>
{% endif %}
{% if level3_topic_list %}
    <ul>
    {% for tp in level3_topic_list %}
        {{ tp.topic_index }} {{ tp.topic_name }};{{ tp.number_of_questions }};{{ tp.number_of_attempted_questions }};{{ tp.number_of_success_first_attempt }};{{ tp.number_of_latest_success_attempt }};{{ tp.avg_first_self_rated_score }};{{ tp.avg_latest_self_rated_score }} <BR>
    {% endfor %}
    </ul>
{% endif %}